### ISSUE TITLE
执行MonkeyTest报IndexError: list index out of range

### ISSUE THREAD

**Issue by Ocean0227** [jtmaxzhu/AppPerformance#3]
--------------开始执行测试----------------
--------------设备：68de2f65 场景2：中等压力下APP性能指标----------------
logcat 完成
traces_log 完成
生成测试报告......
读取文件错误,文件内容为空
------read-------
[]
读取文件错误,文件内容为空
------read-------
[]
读取文件错误,文件内容为空
------read-------
[]
读取文件错误,文件内容为空
------read-------
[]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Users/didi/PycharmProjects/untitled/testCase/MonkeyTest.py", line 235, in run
    start(self.dev)
  File "/Users/didi/PycharmProjects/untitled/testCase/MonkeyTest.py", line 223, in start
    rep.createReport(dev)
  File "/Users/didi/PycharmProjects/untitled/lib/AppReport.py", line 32, in createReport
    pix = lisDevinfo[0][dev]['header']['pix']
IndexError: list index out of range
@jtmaxzhu

**Comment by romantico21** [comment]
一样，楼上解决了吗？

**Comment by jtmaxzhu** [comment]
@romantico21  这是手机信息参数，我是用华为mate8做的测试，好久没搞了，你得自己单独调试一下，有时间我再优化一下，华为mate8 7.0是测试通过的

**Comment by romantico21** [comment]
我用得是小米8，9.0得机器，需要怎么调得？有思路吗，有点懵
